swagger: "2.0"
info:
  version: 1.0.0
  title: REST API
  description: ""
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /reservedpets:
    post:
      description: ""
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              sessionId:
                example: any
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
  /pets/edit/{id}:
    patch:
      description: ""
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                example: any
              sex:
                example: any
              species:
                example: any
              img:
                example: any
              bookedBy:
                example: any
              sessionId:
                example: any
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
  /pets:
    post:
      description: ""
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                example: any
              sex:
                example: any
              species:
                example: any
              img:
                example: any
              sessionId:
                example: any
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
  /pets/{id}:
    delete:
      description: ""
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              sessionId:
                example: any
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
    get:
      description: ""
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
    patch:
      description: ""
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              id:
                example: any
              sessionId:
                example: any
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /pets/available:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
  /users:
    post:
      description: ""
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                example: any
              password:
                example: any
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
  /sessions:
    post:
      description: ""
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                example: any
              password:
                example: any
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    delete:
      description: ""
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              sessionId:
                example: any
      responses:
        "200":
          description: OK
